### ISSUE TITLE
ShinyProxy and Keycloak domains

### ISSUE THREAD

**Issue by anaidv57** [brandones/shiny-keycloak#1]
Hi @brandones, 

I am starting to use ShinyProxy and Keycloak.
ShinyProxy is working in localhost:8180 and Keycloak is working in localhost:8080.
I don't have domains for ShinyProxy and Keycloak. Do you know how I can get a domain locally (I am using Windows)? 
I saw that you have these domains  sp.domain.com and sp-keycloak.domain.com

I would appreciate your help. Thank you. 
Ana

**Comment by SteveLTN** [comment]
@anaidv57 I think you have mentioned the wrong person. I haven't used either ShinyProxy or Keycloak, and I don't have the two domains.

-- Update

Oh, this project uses HTTPS-PORTAL. Now I get why you mention me.
According to the `docker-compose.yml` in this project, if you set your `hosts` in windows, make both domains resolve to `127.0.0.1`, it should work I think.

**Comment by anaidv57** [comment]
> @anaidv57 I think you have mentioned the wrong person. I haven't used either ShinyProxy or Keycloak, and I don't have the two domains.
> 
> -- Update
> 
> Oh, this project uses HTTPS-PORTAL. Now I get why you mention me.
> According to the `docker-compose.yml` in this project, if you set your `hosts` in windows, make both domains resolve to `127.0.0.1`, it should work I think.
Thank you. I am going to try it.

**Comment by brandones** [comment]
Hi Ana,

A domain is a kind of address. It tells other computers on the internet where to find a particular computer. For this reason, there's no such thing as a "local domain," other than `localhost` and `127.0.0.1`, which are the addresses at which your computer finds itself.

If you just want to use this locally, I would just not use HTTPS-PORTAL at all. Remove https-portal from the docker-compose file, set the ShinyProxy `application.yml` to find KeyCloak at `localhost:8080`, and add `localhost:8010/*` to KeyCloak's list of acceptable redirect targets.

If you want to buy a domain, you can at e.g. [NameCheap.com](https://www.namecheap.com/). If you buy the domain "anaidv57.com" (or whatever), you can configure multiple subdomains for free.

Please use Google for additional information about domains, DNS settings, etc.

Good luck,
Brandon

**Comment by anaidv57** [comment]
Thank you. I am going to try it.
Ana

**Comment by anaidv57** [comment]
Hi Brandon, 

Thank you for your help. I have this problem. After click Login in, the browser shows this message “Can’t reach this page”. The log shows:

```
2019-02-06 13:36:16.820 ERROR 1 --- [XNIO-2 task-3] o.k.adapters.OAuthRequestAuthenticator   : failed to turn code into token

java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
```
I would appreciate your help.
Thank you!!! 
Ana

**Comment by brandones** [comment]
Hi Ana, I don’t know what that problem specifically means. I would advise Googling the error message. You should also try and find out whether this error is coming from ShinyProxy or KeyCloak, and check out the `docker logs` for each service.

**Comment by anaidv57** [comment]
Hi Brandon, Thank you. That is the log of ShinyProxy (Docker).

**Comment by brandones** [comment]
Googling "shinyproxy failed to turn code into token" yielded https://github.com/openanalytics/shinyproxy/issues/76, which suggests "Enabling proxy address forwarding" as seen [here](https://hub.docker.com/r/jboss/keycloak/). Please try that and let me know if it works.

**Comment by anaidv57** [comment]
Thanks Brandon. I already did that and it didn't solve the problem.

I tried the same configuration in another computer and the application is working :) . The new computer has Windows 10 Home, so I had to install Docker Toolbox.
Another computer where the application doesn’t work has Windows 10 Education.
This is very strange. I am reaching about this.
